use_frameworks!

platform :ios, '10.0'

target 'NepaliIOSSamayaPicker_Example' do
  pod 'NepaliIOSSamayaPicker', :path => '../'

  target 'NepaliIOSSamayaPicker_Tests' do
    inherit! :search_paths

    
  end
end
